// Mocks generated by Mockito 5.0.14 from annotations
// in riverpod_example/test/post_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dio/dio.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod_example/app/application/models.dart' as _i5;
import 'package:riverpod_example/app/entities/failure.dart' as _i6;
import 'package:riverpod_example/repository/repository.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [IPostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPostRepository extends _i1.Mock implements _i3.IPostRepository {
  MockIPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Post, _i6.Failure>> getPostData(
          {_i7.CancelToken? cancelToken}) =>
      (super.noSuchMethod(
              Invocation.method(#getPostData, [], {#cancelToken: cancelToken}),
              returnValue: Future<_i2.Either<_i5.Post, _i6.Failure>>.value(
                  _FakeEither_0<_i5.Post, _i6.Failure>()))
          as _i4.Future<_i2.Either<_i5.Post, _i6.Failure>>);
  @override
  String toString() => super.toString();
}
